# Nombre del workflow
name: Job Diario  

# Evento que lanza el workflow automáticamente 
on:
  schedule:
    - cron: '0 10 * * *'  # Ejecuta el workflow todos los días a las 10:00 AM (hora UTC)

# Job a ejecutar
jobs:
  job_diario:
    runs-on: labs-runner  # Runner de Stemdo

    steps:
      - name: Job Diario  # Nombre del paso que se mostrará en GitHub Actions
        run: echo "Scheduled job executed!" 
        # Imprime el mensaje 
