# Nombre del workflow
name: Número aleatorio 

# Evento para lanzar el Workflow manualmente
on:
  workflow_dispatch:

jobs:
  random:
    runs-on: labs-runner # Runner de Stemdo
    steps:
      - name: Generar número aleatorio del 1 al 100
      # Genero el número aleatorio, lo muestro por pantalla y lo introduzco en una variable de entorno para utilizarlo posteriormente.
        run: |
          num_random=$(( ( RANDOM % 100 ) + 1 )) 
          echo "Número generado: $num_random"
          echo "num_random=$num_random" >> $GITHUB_ENV 
      # Condicional if. Solo se ejecuta el echo si el número aleatorio es mayor a 50.
      - name: Ejecución cuando número es mayor a 50
        if: ${{ env.num_random > 50 }} 
        run: echo "El número $num_random es mayor a 50"