apiVersion: v1
kind: Service 
metadata: 
  name: {{ include "mip-helm04.fullname" . }}-mysql
  namespace: {{ .Release.Namespace }}
  labels:
    app: mysql
spec:
  type: ClusterIP
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306

  selector:
    app: mysql
