apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mip-helm04.fullname" . }}-phpmyadmin
  namespace: {{ .Release.Namespace }}
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: {{ .Values.phpmyadmin.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: php-configmap
