apiVersion: v1
kind: Service 
metadata: 
  name: {{ include "mip-helm04.fullname" . }}-phpmyadmin
  namespace: {{ .Release.Namespace }}
  labels:
    app: phpmyadmin
spec:
  type: NodePort
  selector:
    app: phpmyadmin
  ports:
    - name: http
      protocol: TCP
      nodePort: {{ .Values.phpmyadmin.nodePort }}
      port: 80
      targetPort: 80

