version: '3.8'

services:
  backend:
    image: mariairenepirvu/gestion-recursos-backmip:latest
    container_name: rrhh-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://137.117.194.84:5432/proyecto_final
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    networks:
      - app-network

  frontend:
    image: mariairenepirvu/gestion-recursos-frontmip:latest
    container_name: rrhh-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
