# Etapa de construcción
# Imagen base
FROM maven:3.9.6-eclipse-temurin-17 AS build
# Establecer el directorio de trabajo
WORKDIR /app
# Copio el proyecto al contenedor
COPY . .
# Compilo el proyecto
RUN mvn clean package -DskipTests
 
# Etapa de ejecución
# Imagen base para la ejecución
FROM eclipse-temurin:17-jdk-alpine
# Establecer el directorio de trabajo
WORKDIR /app
# Copio el archivo JAR construido desde la etapa de construcción
COPY --from=build /app/target/gestion_rrhh.jar app.jar
# Exponer el puerto en el que la aplicación escuchará
EXPOSE 8080
# Comando para ejecutar la aplicación
ENTRYPOINT ["java", "-jar", "app.jar"]