{
 "title": "Dashboard-mip",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Memoria RAM en uso ",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_max_usage_bytes{node=\"minikube\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Espacio libre de disco ",
   "type": "gauge",
   "description": "Esta métrica muestra la suma total del espacio libre disponible en todos los sistemas de archivos montados en el clúster. Utilizo la expresión sum(node_filesystem_free_bytes), que representa la cantidad total de bytes disponibles en disco en todos los nodos del clúster.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_free_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU en uso ",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ancho de banda de entrada y salida",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "sum by() (node_network_receive_bytes_total{job=\"node-exporter\"})",
     "legendFormat": "{{Entrada}}"
    },
    {
     "expr": "sum(node_network_transmit_bytes_total{job=\"node-exporter\"})",
     "legendFormat": "{{Salida}}"
    }
   ]
  }
 ]
}